### ISSUE TITLE
Modify user creation/login to rely on user email

### ISSUE THREAD

**Issue by connorphee** [connorphee/league_app#1]
Currently user creation and login relies a user-defined username. This will be problematic for another issue, resetting passwords. While it is possible to use another method for password reset such as security questions, email seems to be a necessity.

Refactoring needs to be done for the creation and login of users, as well as the userSchema itself.

**Comment by arianahl** [comment]
Hi @connorphee, I will like to help with this issue. 
Are you thinking of some sort of email validation as part of it or do you rely on the user entering a valid email for now?
Also, do you have contribution guidelines for the project?

**Comment by connorphee** [comment]
@arianahl Thank you so much for offering to help. I am writing a contributing and readme as we speak. When I posted these issues last night I did not expect such immediate help! It is a very awesome problem to have!

This is actually a bigger issue than I made it out to be.

I would say for the scope of this ticket, it would be nice to have users register an email address along with a username, and allow either to be entered at login. 

If you want to get started before the doc goes up, just feel free to work on a feature branch, and submit a pull request when you think you have something. Feel free to ask any more questions, as I am sure I forgot something!

**Comment by wildan3105** [comment]
Hi, I think I solved this by #7

**Comment by arianahl89** [comment]
I can see that @wildan3105’s pull request will add the email to the DB and to the HTML but it doesn’t require it to be unique or allow the user to login with the email instead of the username so I will keep working on this. I’m almost done.

**Comment by connorphee** [comment]
@arianahl awesome I look forward to seeing your work!

**Comment by Vishwajeetsinh98** [comment]
@connorphee fix on the way xD

**Comment by Vishwajeetsinh98** [comment]
@connorphee check the pull request [https://github.com/connorphee/league_app/pull/18](https://github.com/connorphee/league_app/pull/18)
