### ISSUE TITLE
Leverage Riot API's for data

### ISSUE THREAD

**Issue by connorphee** [connorphee/league_app#26]
The overall goal of the app is to leverage data provided by Riot games to provide stats and analysis for players. Currently users enter their match info, but we could pull that information from Riot.

**Comment by surmistry** [comment]
Afternoon Connor! Mind if I fork this and tinker around? I've been fighting the urge to play LoL again recently and maybe I'll play with their API's instead :joy:

**Comment by connorphee** [comment]
@surmistry go ahead! I think the first thing to try is getting match data! They also list a way to get mock data as well, but I am on my phone right now and am not able to check.

**Comment by surmistry** [comment]
I was going to approach it as 
1. Input match ID to fetch one match stats
2. Input account ID to fetch all matches
Just got everything up and running and going to play with the API now

**Comment by connorphee** [comment]
Hmm, I would think 2 is where we should start!

**Comment by surmistry** [comment]
Thanks for clarification, should be able to wrap this up in the next couple days hopefully, you only wanted to save the params same as in the 'Create New Match' page, correct?

Except it would be for the entire match, not sure how you want to display it but I can help out with the API integration!

**Comment by connorphee** [comment]
Yes if you could just pull in the match data overall, I could work on display it in the front end! Also, I don't know how much you've worked on, but I would work off of the connorphee/prettier branch as that is what will be merged into master very soon.

**Comment by surmistry** [comment]
Alright I'll move over to that branch and merge what I've been

**Comment by surmistry** [comment]
Just a heads-up, I think RiotDevelopers requires deployed apps to be registered with them to give you a public API Key based on this application process https://developer.riotgames.com/application-process.html

**Comment by connorphee** [comment]
Yes I believe so, but I think they only want applications when the app is considered finished or complete. For now I think we use temp. keys they provide

**Comment by surmistry** [comment]
Hey Connor, I compiled all the data to look like the img attached from the API. I just limitted it to be the recent-most match *for now* to keep my API calls under the limit, but so far the data has:
 
 
-each team looks like the img
-each match is 2 teams
-there are 20 teams in a regular "recent matches" call

<img width="556" alt="screen shot 2017-10-17 at 7 32 39 pm" src="https://user-images.githubusercontent.com/4741146/31694438-4c53d7f6-b372-11e7-91f4-ef39f581a416.png">

**Comment by connorphee** [comment]
@surmistry awesome! I am curious, does each match come with a unique id?

**Comment by surmistry** [comment]
Yeah, so each Summoner's Account has an id

Each Match has
-matchId
-teamId (100, or 200 are the two teams)
-participantId

then the users are assigned Participant Id's and all the data is stored in a huuuge object

So what I did was prompt user to type their Summoner Name in and I chained Api's together to get
-Account Id from summoner name
-Array of recent Match Id's from accountId
-Each individual Match from array of Match Id's

and then made that into a huge array of 20 matches, but hit the API limit pretty quickly so backed off the gas and worked on one match.
*I'm just going to clean up the route bc I'm not sure how you want to handle routing the data to a rendered view* then that should be wrapped up!
