### ISSUE TITLE
Add style enforcement/linting

### ISSUE THREAD

**Issue by connorphee** [connorphee/league_app#9]
As more people start to contribute and the codebase grows, some style enforcement and rules would be good to have. ESLint and Prettier seem to be very popular. I have also used standard in the past, which is very different than most people are used to, but it is very opinionated and easy to setup. Once again, open to anything!

**Comment by ajripley** [comment]
I would like to claim this. I'll be sure to follow your guidelines on contributing. :)

Do you have any preferences on which ESLint rules to enforce? (I recommend AirBnb's style guide rules.)

**Comment by Vishwajeetsinh98** [comment]
@connorphee  Pull request submitted at [https://github.com/connorphee/league_app/pull/10](https://github.com/connorphee/league_app/pull/10)

**Comment by connorphee** [comment]
@ajripley since this already has a PR, would you like to attempt another issue? If you are looking for a good first issue I would be more than happy to find something with you and we could assign it to you!

**Comment by ajripley** [comment]
@connorphee Thanks! If it's okay, I'd love to add a linting command. I filed #11 for the issue.

**Comment by hutchic** [comment]
would https://stickler-ci.com/ suffice?

**Comment by connorphee** [comment]
@hutchic I think we are going to go with eslint for the time being. Thank you for the great suggestion though!

**Comment by connorphee** [comment]
Not sure if error is caused by this or #11 but I am seeing error:

>  Cannot find module /Users/connorphee/projects/league_app/eslint

if someone wants to tackle it, let me know, if not I will fix it.

**Comment by connorphee** [comment]
It actually was unrelated to this issue. I am able to run eslint fine, it relates to another issue that added a script that caused the error. Thank you very much for the PR and closing an issue!

**Comment by Vishwajeetsinh98** [comment]
Sure! Please send other issues. Would love to fix them! xD

**Comment by connorphee** [comment]
If you are feeling super motivated check out #1 an #2, pretty closely related. Running into some roadblocks regarding passport and the way we are doing auth! If not more will come! Thanks again!

**Comment by Vishwajeetsinh98** [comment]
Sure! I'll let you know in a while! :)
